package mapreduce

import (
	"hash/fnv"
	"io/ioutil"
	"os"
	"encoding/json"
	"log"
)

// doMap manages one map task: it reads one of the input files
// (inFile), calls the user-defined map function (mapF) for that file's
// contents, and partitions the output into nReduce intermediate files.
func doMap(
	jobName string, // the name of the MapReduce job
	mapTaskNumber int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(file string, contents string) []KeyValue,
) {
	//
	// You will need to write this function.
	//

	//log.Println(inFile)


	// 读取 input文件所有 字节
	buf , err := ioutil.ReadFile(inFile)
	if err != nil {
		log.Fatal(err)
		// 文件打开失败
	}

	kvs := mapF(inFile, string(buf)) //获得 kvs
	// kv list 结果不能之间写入nReduce个中间文件，需要进过 序列化


	fp := make([]*os.File, nReduce) // 生成 nReduce 个 文件指针
	enc := make([]*json.Encoder, nReduce) // 生成 nReduce个 对应的Encoder

	// 使用文件指针 对Encoder 进行赋值
	for r := 0; r < nReduce; r++ {
		fileName := reduceName(jobName, mapTaskNumber, r) // 获取第r个 中间文件名
		//log.Println(fileName)

		fp[r], err = os.Create(fileName) // 创建第r个文件
		defer  fp[r].Close()

		if err != nil {
			log.Fatal(err)
		}
		enc[r] = json.NewEncoder(fp[r])
	}

	//log.Println(fp, enc)
	for _, kv := range kvs {
		k := kv.Key
		//v := kv.Value

		r := ihash(k) % nReduce // 使用k，进行hash，获得r，即选择第r个中间文件存入当前kv
		err = enc[r].Encode(&kv) // 写入

		if err != nil {
			log.Fatal(err)
		}
	}




	// The intermediate output of a map task is stored as multiple
	// files, one per destination reduce task. The file name includes
	// both the map task number and the reduce task number. Use the
	// filename generated by reduceName(jobName, mapTaskNumber, r) as
	// the intermediate file for reduce task r. Call ihash() (see below)
	// on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
