package main

import "os"
import "fmt"
import (
	"mapreduce"
	"unicode"
	"strings"
	"strconv"
	//"log"
	"sort"
)

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// TODO: you should complete this to do the inverted index challenge

	f := func(c rune) bool{ // 遇到非Letter就split
		return !unicode.IsLetter(c)
	}
	ks := strings.FieldsFunc(value, f) // 所有word

	for _, k := range ks { // 构造 kvs
		kv := mapreduce.KeyValue{k, document}
		res = append(res, kv)
	}

	// key 是 word， value 是 document 文件名
	return res


}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	// TODO: you should complete this to do the inverted index challenge

	var distinctVs []string
	for _, v1 := range values { // 将文件名去重

		flag := false
		for _, v2 := range distinctVs {
			if v1 == v2 {
				flag = true
				break
			}
		}
		if !flag {
			distinctVs = append(distinctVs, v1)
		}
	}

	sort.Strings(distinctVs) // 将文件名排序

	//ans := key
	ans := strconv.Itoa(len(distinctVs)) + " " + strings.Join(distinctVs, ",")
	//log.Fatal(ans)
	return ans
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
	}
}
